# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-15 00:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='upated_at',
            new_name='updated_at',
        ),
    ]
